@host = http://localhost:3000
@usuarioId = 1
@medicoId = 1
@especialidadeId = 1
@pacienteId = 1
@consultaId = 1
@medicamentoId = 1
### ==============================
### LOGIN
### ==============================

# Login (signin) para obter token
POST {{host}}/api/signin
Content-Type: application/json

{
  "email": "luiza.costa@hospitalpb.com",
  "senha": "128"
}
